FROM --platform=$TARGETOS/$TARGETARCH ghcr.io/tinkerbell-community/hook-images/ipmitool:latest

ARG TARGETOS
ARG TARGETARCH

COPY out/tinkerbell-${TARGETOS}-${TARGETARCH} /tinkerbell
ENTRYPOINT [ "/tinkerbell" ]
